---
  - name: Add APT Key for Jenkins
    apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present

  - name: Add APT Repository for Jenkins
    apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

  - name: Update APT Cache
    apt: update_cache=yes

  - name: Install Jenkins
    apt: name=jenkins state=latest

  - name: Ensure Jenkins is running
    service: name=jenkins state=started enabled=yes